# SQL ALCHEMY CAPSTONE PROJECT

### Setup the Engine and the MetaData
* In this part, your job is to create an engine to the database that will be used in this capstone. Then, you need to initialize its metadata.

**Instructions**

* Import `create_engine` and `MetaData` from sqlalchemy.

* Create an engine to the default `sakila` DB by using `mysql+pymysql://root:mysqlpassword123@127.0.0.1/sakila` as the connection string.
* Create a MetaData object as metadata.

In [1]:
from sqlalchemy import create_engine

# use the create_engine function and supply it a connection string that provides the details needed to connect to a DB
engine = create_engine('mysql+pymysql://root:mysqlpassword123@127.0.0.1/sakila') #mysql

# connect method to connect the engine
connection = engine.connect()

* Use `engine.table_names()` with `print` to see the table names

In [2]:
print(engine.table_names())

['actor', 'address', 'category', 'city', 'country', 'customer', 'film', 'film_actor', 'film_category', 'film_text', 'inventory', 'language', 'payment', 'rental', 'staff', 'store']


* Wow, lot's of table names. Let's proceed with `actor`
* To call the table inside our DB, 
    * Import `MetaData` and `Table` from `sqlalchemy`
    * Create `MetaData()` object and set it to `metadata` variable.
    * Create `actor` table in sqlalchemy enviroment.

In [3]:
# Reflection reads DB and builds SQLAlchemy Table objects
from sqlalchemy import MetaData, Table
metadata = MetaData() # MetaData object is a catalog that stores DB information such as tables 

actor = Table("actor", metadata, autoload = True, autoload_with=engine) # "country" is our DB Table name, 
# metadata is our metadata instance
# autoload = True: it'll load the data automatically
# autoload_with=engine: it'll autoload from the engine

print(repr(actor)) # to view the details of our table that we stored as census
# This allows us to see the names of the columns along with their types

Table('actor', MetaData(bind=None), Column('actor_id', SMALLINT(unsigned=True), table=<actor>, primary_key=True, nullable=False), Column('first_name', VARCHAR(length=45), table=<actor>, nullable=False), Column('last_name', VARCHAR(length=45), table=<actor>, nullable=False), Column('last_update', TIMESTAMP(), table=<actor>, nullable=False, server_default=DefaultClause(<sqlalchemy.sql.elements.TextClause object at 0x000001BBC7D35BB0>, for_update=False)), schema=None)


* Use `.columns.keys()`to see the column names of `actor`

In [4]:
actor.columns.keys()

['actor_id', 'first_name', 'last_name', 'last_update']

- `actor_id` is an int value that is given by each actor consequently.
- `first_name` is name of the actors.
- `last_name` is surname of the actors.
- `last_update` is the last time their info entered to this table.

### DATA MANIPULATION WITH SQLALCHEMY

* Use `select` method to print values inside our `actor`table.
# QUERY YOLU

* **stmt = "SELECT * FROM country"**  this is how we write statements in SQLAlchemy
* Hocam bu yoldan sonrasinda `execute()` ve `result_proxy.fetchall()` methodlari kullaniliyor ancak bu iki method disinda SQLAlchemy methodu kullanmaya gerek yok.

In [5]:
from sqlalchemy import select
# stmt = "SELECT * FROM country" # this is how we write statements ins SQLAlchemy
stmt = select([actor]) # or we can also write like this
result_proxy = connection.execute(stmt) # this is how we execute results in SQLAlchemy
results = result_proxy.fetchall() # this is how we fetch the result in SQLAlchemy
results # to see the all data on the country table

[(1, 'PENELOPE', 'GUINESS', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (2, 'NICK', 'WAHLBERG', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (3, 'ED', 'CHASE', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (4, 'JENNIFER', 'DAVIS', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (5, 'JOHNNY', 'LOLLOBRIGIDA', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (6, 'BETTE', 'NICHOLSON', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (7, 'GRACE', 'MOSTEL', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (8, 'MATTHEW', 'JOHANSSON', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (9, 'JOE', 'SWANK', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (10, 'CHRISTIAN', 'GABLE', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (11, 'ZERO', 'CAGE', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (12, 'KARL', 'BERRY', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (13, 'UMA', 'WOOD', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (14, 'VIVIEN', 'BERGEN', datetime.datetime(2006, 2, 15, 3, 34, 33)),
 (15, 'CUBA', 'OLIVIER', datetime

* So we have 200 actors in total, along with their id, name, surname and last time their info entered to this table.
* Use mappings to see the first row of `actor` table.

In [6]:
results[0]

(1, 'PENELOPE', 'GUINESS', datetime.datetime(2006, 2, 15, 3, 34, 33))

* Again, use mappings to see the first value of `actor` table.

In [7]:
results[0]["actor_id"] # "Code" is the name of the first column

1

* Let's find the first name of the actor whose ID is 10.
* Use `where` method for that purpose.

In [8]:
from sqlalchemy import select
stmt = select([actor])

stmt = stmt.where(actor.columns.actor_id == "10")
results = connection.execute(stmt).fetchall() # fetching our data

print("First name of the actor whose id is 10: ")
# Using for loop for more clean output
for result in results:
    print(result.first_name)

First name of the actor whose id is 10: 
CHRISTIAN


* Let's query now the actors whose name is TOM or whose surname is PITT
* To do that, use `where` with `_or`

In [9]:
from sqlalchemy import or_
stmt = select([actor])

# Actors whose name is TOM or whose surname is PITT
stmt = stmt.where(or_(actor.columns.first_name == "TOM",
                  actor.columns.last_name == "PITT"))
results = connection.execute(stmt).fetchall() # fetching our data

# first name of those actors
print("Actors whose name is TOM or whose surname is PITT: ")
# Using for loop for more clean output
for result in results:
    print(result.first_name)

Actors whose name is TOM or whose surname is PITT: 
TOM
TOM
JAMES


* Let's query  a spesific actor: HENRY CAVILL
* To do that, use `where` with `_and`

In [10]:
from sqlalchemy import and_
stmt = select([actor])

# See that if we have HENRY CAVILL in our DB or not
stmt = stmt.where(and_(actor.columns.first_name == "HENRY",
                  actor.columns.last_name == "CAVILL"))
results = connection.execute(stmt).fetchall() # fetching our data
print("Do we have Henry Cavill in our DB? ")
# Using for loop for more clean output
for result in results:
    print(result.first_name, result.last_name)

Do we have Henry Cavill in our DB? 


* Let's query now the actors whose last update is not on 2000
* To do that, use `where` with `_not`

In [11]:
from sqlalchemy import not_
stmt = select([actor])

# Not Republicly governed
stmt = stmt.where(not_(actor.columns.last_update == 2000))
results = connection.execute(stmt).fetchall() # fetching our data

# countries
print("Actors whose last update is not on 2000: ")
# Using for loop for more clean output
for result in results:
    print(result.last_update)

Actors whose last update is not on 2000: 
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:33
2006-02-15 03:34:3

* It seems that we have a lot of actors whose last update to our table is not 2000. Interestingly, all of those actors are updated in 2006-02-15 04:34:33. Let's doublecheck it by using `order_by`

In [12]:
from sqlalchemy import and_
stmt = select([actor])

stmt = stmt.order_by(actor.columns.last_update)

# Ordering actors by their last update date: 
results = connection.execute(stmt).fetchall() # fetching our data

print("Ordering actors by their last update date: ")
# Using for loop for more clean output
for result in results:
    print(result.last_update, result.first_name)

Ordering actors by their last update date: 
2006-02-15 03:34:33 PENELOPE
2006-02-15 03:34:33 NICK
2006-02-15 03:34:33 ED
2006-02-15 03:34:33 JENNIFER
2006-02-15 03:34:33 JOHNNY
2006-02-15 03:34:33 BETTE
2006-02-15 03:34:33 GRACE
2006-02-15 03:34:33 MATTHEW
2006-02-15 03:34:33 JOE
2006-02-15 03:34:33 CHRISTIAN
2006-02-15 03:34:33 ZERO
2006-02-15 03:34:33 KARL
2006-02-15 03:34:33 UMA
2006-02-15 03:34:33 VIVIEN
2006-02-15 03:34:33 CUBA
2006-02-15 03:34:33 FRED
2006-02-15 03:34:33 HELEN
2006-02-15 03:34:33 DAN
2006-02-15 03:34:33 BOB
2006-02-15 03:34:33 LUCILLE
2006-02-15 03:34:33 KIRSTEN
2006-02-15 03:34:33 ELVIS
2006-02-15 03:34:33 SANDRA
2006-02-15 03:34:33 CAMERON
2006-02-15 03:34:33 KEVIN
2006-02-15 03:34:33 RIP
2006-02-15 03:34:33 JULIA
2006-02-15 03:34:33 WOODY
2006-02-15 03:34:33 ALEC
2006-02-15 03:34:33 SANDRA
2006-02-15 03:34:33 SISSY
2006-02-15 03:34:33 TIM
2006-02-15 03:34:33 MILLA
2006-02-15 03:34:33 AUDREY
2006-02-15 03:34:33 JUDY
2006-02-15 03:34:33 BURT
2006-02-15 03:34:33 

* Let's now order the actors by their id's descendently.
* Use `.desc()` for that purpose

In [13]:
from sqlalchemy import and_
stmt = select([actor])

stmt = stmt.order_by(actor.columns.actor_id.desc())

# Ordering actors by their id's descendently: 
results = connection.execute(stmt).fetchall() # fetching our data

# Using for loop for more clean output
print("Ordering actors by their id's descendently: ")
for result in results:
    print(result.first_name, result.last_name)

Ordering actors by their id's descendently: 
Serkan keskin
Erdal Besikcioglu
Okan YALABIK
Serkan KESKIN
Okan Yalabik
Okan Yalabik
THORA YALABIK
JULIA FAWCETT
MARY KEITEL
REESE WEST
BELA WALKEN
JAYNE SILVERSTONE
MERYL ALLEN
BURT TEMPLE
JOHN SUVARI
GREGORY GOODING
AUDREY BAILEY
CUBA BIRCH
ROCK DUKAKIS
RENEE BALL
JULIA ZELLWEGER
MICHAEL BOLGER
HUMPHREY GARLAND
RUSSELL CLOSE
DEBBIE AKROYD
MATTHEW CARREY
JEFF SILVERSTONE
ED GUINESS
LISA MONROE
GENE MCKELLEN
JON CHASE
WILLIAM HACKMAN
MICHAEL BENING
ALAN DREYFUSS
GROUCHO WILLIAMS
OLYMPIA PFEIFFER
MENA HOPPER
KENNETH HOFFMAN
WILL WILSON
LAURENCE BULLOCK
NICK DEGENERES
AL GARLAND
HUMPHREY WILLIS
CHRISTOPHER WEST
OPRAH KILMER
HARVEY HOPE
CHRIS DEPP
LAURA BRODY
VIVIEN BASINGER
GRETA MALDEN
FAY WOOD
IAN TANDY
MERYL GIBSON
MINNIE KILMER
BEN HARRIS
GEOFFREY HESTON
JAYNE NOLTE
RUSSELL TEMPLE
EMILY DEE
FAY WINSLET
ALBERT JOHANSSON
KIM ALLEN
ANGELA WITHERSPOON
RIVER DEAN
JADA RYDER
CATE HARRIS
WHOOPI HURT
EWAN GOODING
LUCILLE DEE
MORGAN WILLIAMS
ED MAN

* Count how many actors we have.
* To do that, use `count` with `func` and count actor_id 's

In [14]:
from sqlalchemy import func
# Counting the population of the countries in DB 
stmt = select([func.count(actor.columns.actor_id)])
results = connection.execute(stmt).scalar()
print(results)

206


* Print to see how many tables we have in our DB

In [15]:
print(engine.table_names())

['actor', 'address', 'category', 'city', 'country', 'customer', 'film', 'film_actor', 'film_category', 'film_text', 'inventory', 'language', 'payment', 'rental', 'staff', 'store']


Create `film_actor`table with the same way you did while creating `actor` table.

In [16]:
film_actor = Table("film_actor", metadata, autoload = True, autoload_with=engine)

* Print keynames of `film_actor` table.

In [17]:
film_actor.columns.keys()

['actor_id', 'film_id', 'last_update']

* Use `select` method to print values inside our `film_actor`table.

In [18]:
from sqlalchemy import select
# stmt = "SELECT * FROM country" # this is how we write statements ins SQLAlchemy
stmt = select([film_actor]) # or we can also write like this
result_proxy = connection.execute(stmt) # this is how we execute results in SQLAlchemy
results = result_proxy.fetchall() # this is how we fetch the result in SQLAlchemy
results # to see the all data on the country table

[(1, 1, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 23, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 25, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 106, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 140, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 166, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 277, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 361, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 438, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 499, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 506, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 509, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 605, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 635, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 749, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 832, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 939, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 970, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (1, 980, datetime.datetime(2006, 2, 15, 4, 5, 3)),
 (2, 3, datetime

* Seems that lots of data we have in `film_actor` table. 
* Count the number of rows to learn how many row we have in `film_actor` table.

In [19]:
from sqlalchemy import func
# Counting the population of the countries in DB 
stmt = select([func.count(film_actor.columns.actor_id)])
results = connection.execute(stmt).scalar()
print(results)

5462


* Automatic join `actor` tables `actor_id` column with `film_actor` table's `actor_id` column.

In [21]:
stmt = select([actor.columns.actor_id, film_actor.columns.actor_id])
stmt = stmt.limit(8)
results = connection.execute(stmt).fetchall()
print(results)

[(186, 1), (111, 1), (85, 1), (300, 1), (203, 1), (202, 1), (200, 1), (63, 1)]


* Add a new actor at the end of the `actor` table and print the last row to check whether he updated or not. Actor's info: Okan Yalabik, id = 300, last update date: 01.01.2022 22:15 00:00

In [23]:
# importing necessary statement
from sqlalchemy import insert

# Let's insert a row to our newly created nations table
stmt = insert(actor).values(actor_id = 550, first_name = "Okan", last_name = "Yalabik", last_update = "2022-01-01 22:15:00") # entering the values we want to insert
result_proxy = connection.execute(stmt)
print("Our row number inside actor is: ", result_proxy.rowcount) # To count how many rows we have inside our actors table

Our row number inside actor is:  1


In [35]:
stmt = select([actor])
result = connection.execute(stmt).fetchall()
print("Values inside our actors table: ", result[200])

Values inside our actors table:  (202, 'Okan', 'Yalabik', datetime.datetime(2021, 1, 1, 21, 15))


* Insert the following actors at the end of the `actor` table.

    * Erdal Besikcioglu, id = 301, last update date: 01.01.2022 22:15 00:00
    * Serkan Keskin, id = 302, last update date: 01.01.2022 22:15 00:00
`

In [37]:
stmt = insert(actor)

# dict that contains multiple rows 
values_list = [{"actor_id" : 2005, "first_name" : "Erdal", "last_name" : "Besikcioglu", "last_update" : "2021-01-01 22:15:00"},
               {"actor_id" : 2006, "first_name" : "Serkan", "last_name" : "keskin", "last_update" : "2021-01-01 22:15:00"}]

result_proxy = connection.execute(stmt, values_list)
print("how many rows we added inside actor table: ", result_proxy.rowcount) # To count how many rows we added our nations table

how many rows we added inside actor table:  2


In [40]:
stmt = select([actor])
result = connection.execute(stmt).fetchall()
print("last - 1'th row: ", result[204]) # result[201]
print("last row: ", result[205]) # result[202]

last - 1'th row:  (301, 'Erdal', 'Besikcioglu', datetime.datetime(2021, 1, 1, 21, 15))
last row:  (302, 'Serkan', 'keskin', datetime.datetime(2021, 1, 1, 21, 15))


* Update uppercase Okan Yalabik, Erdal Besikcioglu, and Serkan Keskin with Okan YALABIK, Erdal BESİKCİOGLU AND Serkan KESKİN by using `update`

In [89]:
# FOR Okan YALABIK
# importing necessary statement
from sqlalchemy import update

stmt = update(actor) # to point out that which table are we going to update

stmt = stmt.where(actor.columns.actor_id == 201) # importing the row that's id value is 200

stmt = stmt.values(last_name='YALABIK') 
result_proxy = connection.execute(stmt)
print("To see how may rows we've updated in this code block: ",result_proxy.rowcount)

stmt = select([actor])
result = connection.execute(stmt).fetchall()
print("Updated Value: ", result[200])

To see how may rows we've updated in this code block:  1
Updated Value:  (201, 'Okan', 'YALABIK', datetime.datetime(2022, 1, 1, 22, 46, 36))


In [93]:
# for Erdal BESIKCIOGLU
# importing necessary statement
from sqlalchemy import update

stmt = update(actor) # to point out that which table are we going to update

stmt = stmt.where(actor.columns.actor_id == 205) # importing the row that's id value is 204

stmt = stmt.values(last_name='BESIKCIOGLU') 
result_proxy = connection.execute(stmt)
print("To see how may rows we've updated in this code block: ",result_proxy.rowcount)

stmt = select([actor])
result = connection.execute(stmt).fetchall()
print("Updated Value: ", result[204])

To see how may rows we've updated in this code block:  1
Updated Value:  (205, 'Erdal', 'BESIKCIOGLU', datetime.datetime(2022, 1, 1, 22, 52))


In [94]:
# for Serkan KESKIN
# importing necessary statement
from sqlalchemy import update

stmt = update(actor) # to point out that which table are we going to update

stmt = stmt.where(actor.columns.actor_id == 206) # importing the row that's id value is 204

stmt = stmt.values(last_name='KESKIN') 
result_proxy = connection.execute(stmt)
print("To see how may rows we've updated in this code block: ",result_proxy.rowcount)

stmt = select([actor])
result = connection.execute(stmt).fetchall()
print("Updated Value: ", result[205])

To see how may rows we've updated in this code block:  1
Updated Value:  (206, 'Serkan', 'KESKIN', datetime.datetime(2022, 1, 1, 22, 52, 36))


* Delete the rows whose actor_id is 201, 204, 205 by using `delete`

In [41]:
from sqlalchemy import delete
stmt = delete(actor).where(actor.columns.actor_id == 201) # Deleting the Name Column
result_proxy = connection.execute(stmt)
result_proxy.rowcount # to count how many rows affected

0

In [102]:
from sqlalchemy import delete
stmt = delete(actor).where(actor.columns.actor_id == 204) # Deleting the Name Column
result_proxy = connection.execute(stmt)
result_proxy.rowcount # to count how many rows affected

1

In [103]:
from sqlalchemy import delete
stmt = delete(actor).where(actor.columns.actor_id == 205) # Deleting the Name Column
result_proxy = connection.execute(stmt)
result_proxy.rowcount # to count how many rows affected

1